"""User-space MediaMTX lifecycle bound to the ROCK 4D wlan0 address."""

from __future__ import annotations

from dataclasses import asdict, dataclass
import json
import os
from pathlib import Path
import shutil
import signal
import socket
import subprocess
import time

from openframetap.network.interfaces import (
    NetworkPreflightError,
    audit_wlan0,
    is_rfc1918,
    port_is_available,
)
from openframetap.network.reachability import tcp_reachable


MEDIAMTX_VERSION = "v1.18.2"
MEDIAMTX_ASSET = "mediamtx_v1.18.2_linux_arm64.tar.gz"
MEDIAMTX_SHA256 = "c78aa7a1bdab94b2b02be364661f17802143215dba37e1fa67c3e0849248b485"
MEDIAMTX_SOURCE = "https://github.com/bluenviron/mediamtx/releases/tag/v1.18.2"


@dataclass(frozen=True, slots=True)
class RtmpPaths:
    root: Path
    binary: Path
    config: Path
    pid_file: Path
    log_file: Path

    @classmethod
    def under(cls, root: Path) -> "RtmpPaths":
        root = root.resolve()
        return cls(
            root=root,
            binary=root / "bin" / "mediamtx",
            config=root / "mediamtx.yml",
            pid_file=root / "mediamtx.pid",
            log_file=root / "server.log",
        )


@dataclass(frozen=True, slots=True)
class ServerStatus:
    state: str
    pid: int | None
    listener_address: str
    listener_reachable: bool
    binary_version: str | None
    log_file: str
    warning: str | None = None

    def to_dict(self) -> dict:
        return asdict(self)


def media_mtx_config(ipv4: str, *, port: int = 1935) -> str:
    if not is_rfc1918(ipv4):
        raise NetworkPreflightError("MediaMTX must bind a wlan0 RFC1918 address")
    return f"""# Generated by OpenFrameTap. Do not add secrets here.
logLevel: info
logDestinations: [stdout]
api: false
metrics: false
pprof: false
playback: false
rtsp: false
rtmp: true
rtmpAddress: {ipv4}:{port}
hls: false
webrtc: false
srt: false
pathDefaults:
  source: publisher
paths:
  all_others:
"""


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return True


class RtmpServer:
    def __init__(self, paths: RtmpPaths, ipv4: str, *, port: int = 1935) -> None:
        if not is_rfc1918(ipv4):
            raise NetworkPreflightError("RTMP listener must use a wlan0 RFC1918 address")
        self.paths = paths
        self.ipv4 = ipv4
        self.port = port

    @property
    def listener_address(self) -> str:
        return f"{self.ipv4}:{self.port}"

    def _read_pid(self) -> int | None:
        try:
            raw = self.paths.pid_file.read_text(encoding="ascii").strip()
            pid = int(raw)
        except (FileNotFoundError, ValueError):
            self.paths.pid_file.unlink(missing_ok=True)
            return None
        if pid <= 1 or not _pid_alive(pid):
            self.paths.pid_file.unlink(missing_ok=True)
            return None
        return pid

    def _owns_pid(self, pid: int) -> bool:
        command_line = Path(f"/proc/{pid}/cmdline")
        if not command_line.exists():
            return True
        try:
            rendered = command_line.read_bytes().replace(b"\x00", b" ").decode(
                "utf-8", errors="replace"
            )
        except OSError:
            return False
        return str(self.paths.binary) in rendered or self.paths.binary.name in rendered

    def binary_version(self) -> str | None:
        if not self.paths.binary.is_file():
            return None
        result = subprocess.run(
            [str(self.paths.binary), "--version"],
            text=True,
            capture_output=True,
            check=False,
            timeout=5,
        )
        rendered = (result.stdout + result.stderr).strip().splitlines()
        return rendered[0] if rendered else None

    def status(self) -> ServerStatus:
        pid = self._read_pid()
        reachable = tcp_reachable(self.ipv4, self.port, timeout=0.25)
        warning = None
        if pid is not None and not self._owns_pid(pid):
            warning = "PID file points to a process not owned by this MediaMTX runtime"
            state = "ownership_mismatch"
        elif pid is not None and reachable:
            state = "running"
        elif pid is not None:
            state = "starting_or_unhealthy"
        elif reachable:
            state = "foreign_listener"
        else:
            state = "stopped"
        return ServerStatus(
            state=state,
            pid=pid,
            listener_address=self.listener_address,
            listener_reachable=reachable,
            binary_version=self.binary_version(),
            log_file=str(self.paths.log_file),
            warning=warning,
        )

    def start(self, *, timeout: float = 8.0) -> ServerStatus:
        before = self.status()
        if before.state == "running":
            return before
        if before.state != "stopped":
            raise RuntimeError(f"refusing start while server state is {before.state}")
        if not self.paths.binary.is_file() or not os.access(self.paths.binary, os.X_OK):
            raise FileNotFoundError(f"MediaMTX binary missing or not executable: {self.paths.binary}")
        if not port_is_available(self.ipv4, self.port):
            raise RuntimeError(f"RTMP port already occupied on {self.listener_address}")
        self.paths.root.mkdir(parents=True, exist_ok=True)
        self.paths.config.write_text(media_mtx_config(self.ipv4, port=self.port), encoding="utf-8")
        if os.name != "nt":
            self.paths.root.chmod(0o700)
            self.paths.config.chmod(0o600)
        log_stream = self.paths.log_file.open("ab", buffering=0)
        try:
            process = subprocess.Popen(
                [str(self.paths.binary), str(self.paths.config)],
                cwd=self.paths.root,
                stdin=subprocess.DEVNULL,
                stdout=log_stream,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        finally:
            log_stream.close()
        self.paths.pid_file.write_text(f"{process.pid}\n", encoding="ascii")
        if os.name != "nt":
            self.paths.pid_file.chmod(0o600)
            self.paths.log_file.chmod(0o600)
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if process.poll() is not None:
                self.paths.pid_file.unlink(missing_ok=True)
                raise RuntimeError(
                    f"MediaMTX exited during startup with status {process.returncode}; inspect {self.paths.log_file}"
                )
            if tcp_reachable(self.ipv4, self.port, timeout=0.2):
                current = self.status()
                if current.state == "running":
                    return current
                # A shebang-based test/helper can briefly retain the parent's
                # cmdline between fork and exec. Keep the ownership check
                # strict, but do not expose that transient state as success.
                if current.state != "ownership_mismatch":
                    raise RuntimeError(
                        f"listener became reachable while server state is {current.state}"
                    )
            time.sleep(0.1)
        self.stop(timeout=2.0)
        raise TimeoutError(f"MediaMTX did not listen on {self.listener_address}")

    def stop(self, *, timeout: float = 8.0) -> ServerStatus:
        pid = self._read_pid()
        if pid is None:
            return self.status()
        if not self._owns_pid(pid):
            raise RuntimeError("refusing to signal a PID not owned by this MediaMTX runtime")
        os.kill(pid, signal.SIGTERM)
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline and _pid_alive(pid):
            time.sleep(0.1)
        if _pid_alive(pid):
            os.kill(pid, signal.SIGKILL)
            deadline = time.monotonic() + 2.0
            while time.monotonic() < deadline and _pid_alive(pid):
                time.sleep(0.05)
        self.paths.pid_file.unlink(missing_ok=True)
        return self.status()


def default_paths() -> RtmpPaths:
    root = Path(os.environ.get("OPENFRAMETAP_RTMP_RUNTIME", "runtime/rtmp"))
    return RtmpPaths.under(root)


def make_server() -> RtmpServer:
    snapshot = audit_wlan0()
    return RtmpServer(default_paths(), snapshot.ipv4)


def server_doctor(*, lifecycle_check: bool = True) -> dict:
    snapshot = audit_wlan0()
    server = RtmpServer(default_paths(), snapshot.ipv4)
    initial = server.status()
    lifecycle = None
    if lifecycle_check and initial.state == "stopped":
        started = server.start()
        stopped = server.stop()
        lifecycle = {
            "started": started.state == "running",
            "stopped": stopped.state == "stopped",
            "pid_cleaned": not server.paths.pid_file.exists(),
        }
    return {
        "network": snapshot.to_dict(),
        "listener_address": server.listener_address,
        "port_available_before": initial.state == "stopped",
        "binary": str(server.paths.binary),
        "binary_version": server.binary_version(),
        "expected_version": MEDIAMTX_VERSION,
        "release_source": MEDIAMTX_SOURCE,
        "asset": MEDIAMTX_ASSET,
        "asset_sha256": MEDIAMTX_SHA256,
        "ffmpeg": shutil.which("ffmpeg"),
        "ffprobe": shutil.which("ffprobe"),
        "gstreamer": shutil.which("gst-launch-1.0"),
        "lifecycle_check": lifecycle,
        "status_after": server.status().to_dict(),
    }
